var datosProde = [
    {
        "id": 1,
        "dia": "DOMINGO",
        "fecha": "20/11/2022",
        "hora": "13:00",
        "local": "QATAR",
        "icolocal": "qatar",
        "visitante": "ECUADOR",
        "icovisitante": "ecuador",
        "grupo": "GRUPO A",
        "fecha_n": 1,
        "user": "prueba@prueba.com",
        "user_v": 1,
        "partido_n": 1,
        "prode_resul": "L",
        "prode_l": 0,
        "prode_v": 1,
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "L",
        "resul_l": 1,
        "resul_v": 0,
        "resul_pl": "",
        "resul_pv": "",
        "puntos": 0
    },
    {
        "id": 2,
        "dia": "LUNES",
        "fecha": "21/11/2022",
        "hora": "10:00",
        "local": "INGLATERRA",
        "icolocal": "inglaterra",
        "visitante": "IRÁN",
        "icovisitante": "iran",
        "grupo": "GRUPO B",
        "fecha_n": 1,
        "user": "prueba@prueba.com",
        "user_v": 2,
        "partido_n": 2,
        "prode_resul": "E",
        "prode_l": 2,
        "prode_v": 3,
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "V",
        "resul_l": 2,
        "resul_v": 3,
        "resul_pl": "",
        "resul_pv": "",
        "puntos": 3
    },
    {
        "id": 3,
        "dia": "LUNES",
        "fecha": "21/11/2022",
        "hora": "13:00",
        "local": "SENEGAL",
        "icolocal": "senegal",
        "visitante": "PAÍSES BAJOS",
        "icovisitante": "paisesbajos",
        "grupo": "GRUPO A",
        "fecha_n": 1,
        "user": "prueba@prueba.com",
        "user_v": 3,
        "partido_n": 3,
        "prode_resul": "V",
        "prode_l": 4,
        "prode_v": 5,
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "E",
        "resul_l": 4,
        "resul_v": 4,
        "resul_pl": "",
        "resul_pv": "",
        "puntos": 0
    },
    {
        "id": 4,
        "dia": "LUNES",
        "fecha": "21/11/2022",
        "hora": "16:00",
        "local": "ESTADOS UNIDOS",
        "icolocal": "estadosunidos",
        "visitante": "GALES",
        "icovisitante": "gales",
        "grupo": "GRUPO B",
        "fecha_n": 1,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 4,
        "prode_resul": "E",
        "prode_l": 6,
        "prode_v": 6,
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "E",
        "resul_l": 6,
        "resul_v": 6,
        "resul_pl": "",
        "resul_pv": "",
        "puntos": 1
    },
    {
        "id": 5,
        "dia": "MARTES",
        "fecha": "22/11/2022",
        "hora": "07:00",
        "local": "ARGENTINA",
        "icolocal": "argentina",
        "visitante": "ARABIA SAUDITA",
        "icovisitante": "arabiasaudita",
        "grupo": "GRUPO C",
        "fecha_n": 1,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 5,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 6,
        "dia": "MARTES",
        "fecha": "22/11/2022",
        "hora": "10:00",
        "local": "DINAMARCA",
        "icolocal": "dinamarca",
        "visitante": "TÚNEZ",
        "icovisitante": "tunez",
        "grupo": "GRUPO D",
        "fecha_n": 1,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 6,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 7,
        "dia": "MARTES",
        "fecha": "22/11/2022",
        "hora": "13:00",
        "local": "MÉXICO",
        "icolocal": "mexico",
        "visitante": "POLONIA",
        "icovisitante": "polonia",
        "grupo": "GRUPO C",
        "fecha_n": 1,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 7,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 8,
        "dia": "MARTES",
        "fecha": "22/11/2022",
        "hora": "16:00",
        "local": "FRANCIA",
        "icolocal": "francia",
        "visitante": "AUSTRALIA",
        "icovisitante": "australia",
        "grupo": "GRUPO D",
        "fecha_n": 1,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 8,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 9,
        "dia": "MIÉRCOLES",
        "fecha": "23/11/2022",
        "hora": "07:00",
        "local": "MARRUECOS",
        "icolocal": "marruecos",
        "visitante": "CROACIA",
        "icovisitante": "croacia",
        "grupo": "GRUPO F",
        "fecha_n": 1,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 9,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 10,
        "dia": "MIÉRCOLES",
        "fecha": "23/11/2022",
        "hora": "10:00",
        "local": "ALEMANIA",
        "icolocal": "alemania",
        "visitante": "JAPÓN",
        "icovisitante": "japon",
        "grupo": "GRUPO E",
        "fecha_n": 1,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 10,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 11,
        "dia": "MIÉRCOLES",
        "fecha": "23/11/2022",
        "hora": "13:00",
        "local": "ESPAÑA",
        "icolocal": "espana",
        "visitante": "COSTA RICA",
        "icovisitante": "costarica",
        "grupo": "GRUPO E",
        "fecha_n": 1,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 11,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 12,
        "dia": "MIÉRCOLES",
        "fecha": "23/11/2022",
        "hora": "16:00",
        "local": "BÉLGICA",
        "icolocal": "belgica",
        "visitante": "CANADÁ",
        "icovisitante": "canada",
        "grupo": "GRUPO F",
        "fecha_n": 1,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 12,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 13,
        "dia": "JUEVES",
        "fecha": "24/11/2022",
        "hora": "07:00",
        "local": "SUIZA",
        "icolocal": "suiza",
        "visitante": "CAMERÚN",
        "icovisitante": "camerun",
        "grupo": "GRUPO G",
        "fecha_n": 1,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 13,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 14,
        "dia": "JUEVES",
        "fecha": "24/11/2022",
        "hora": "10:00",
        "local": "URUGUAY",
        "icolocal": "uruguay",
        "visitante": "COREA",
        "icovisitante": "corea",
        "grupo": "GRUPO H",
        "fecha_n": 1,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 14,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 15,
        "dia": "JUEVES",
        "fecha": "24/11/2022",
        "hora": "13:00",
        "local": "PORTUGAL",
        "icolocal": "portugal",
        "visitante": "GHANA",
        "icovisitante": "ghana",
        "grupo": "GRUPO H",
        "fecha_n": 1,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 15,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 16,
        "dia": "JUEVES",
        "fecha": "24/11/2022",
        "hora": "16:00",
        "local": "BRASIL",
        "icolocal": "brasil",
        "visitante": "SERBIA",
        "icovisitante": "serbia",
        "grupo": "GRUPO G",
        "fecha_n": 1,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 16,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 17,
        "dia": "VIERNES",
        "fecha": "25/11/2022",
        "hora": "07:00",
        "local": "GALES",
        "icolocal": "gales",
        "visitante": "IRÁN",
        "icovisitante": "iran",
        "grupo": "GRUPO B",
        "fecha_n": 2,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 17,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 18,
        "dia": "VIERNES",
        "fecha": "25/11/2022",
        "hora": "10:00",
        "local": "QATAR",
        "icolocal": "qatar",
        "visitante": "SENEGAL",
        "icovisitante": "senegal",
        "grupo": "GRUPO A",
        "fecha_n": 2,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 18,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 19,
        "dia": "VIERNES",
        "fecha": "25/11/2022",
        "hora": "13:00",
        "local": "PAÍSES BAJOS",
        "icolocal": "paisesbajos",
        "visitante": "ECUADOR",
        "icovisitante": "ecuador",
        "grupo": "GRUPO A",
        "fecha_n": 2,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 19,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 20,
        "dia": "VIERNES",
        "fecha": "25/11/2022",
        "hora": "16:00",
        "local": "INGLATERRA",
        "icolocal": "inglaterra",
        "visitante": "ESTADOS UNIDOS",
        "icovisitante": "estadosunidos",
        "grupo": "GRUPO B",
        "fecha_n": 2,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 20,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 21,
        "dia": "SÁBADO",
        "fecha": "26/11/2022",
        "hora": "07:00",
        "local": "TÚNEZ",
        "icolocal": "tunez",
        "visitante": "AUSTRALIA",
        "icovisitante": "australia",
        "grupo": "GRUPO D",
        "fecha_n": 2,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 21,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 22,
        "dia": "SÁBADO",
        "fecha": "26/11/2022",
        "hora": "10:00",
        "local": "POLONIA",
        "icolocal": "polonia",
        "visitante": "ARABIA SAUDITA",
        "icovisitante": "arabiasaudita",
        "grupo": "GRUPO C",
        "fecha_n": 2,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 22,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 23,
        "dia": "SÁBADO",
        "fecha": "26/11/2022",
        "hora": "13:00",
        "local": "FRANCIA",
        "icolocal": "francia",
        "visitante": "DINAMARCA",
        "icovisitante": "dinamarca",
        "grupo": "GRUPO D",
        "fecha_n": 2,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 23,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 24,
        "dia": "SÁBADO",
        "fecha": "26/11/2022",
        "hora": "16:00",
        "local": "ARGENTINA",
        "icolocal": "argentina",
        "visitante": "MÉXICO",
        "icovisitante": "mexico",
        "grupo": "GRUPO C",
        "fecha_n": 2,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 24,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 25,
        "dia": "DOMINGO",
        "fecha": "27/11/2022",
        "hora": "07:00",
        "local": "JAPÓN",
        "icolocal": "japon",
        "visitante": "COSTA RICA",
        "icovisitante": "costarica",
        "grupo": "GRUPO E",
        "fecha_n": 2,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 25,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 26,
        "dia": "DOMINGO",
        "fecha": "27/11/2022",
        "hora": "10:00",
        "local": "BÉLGICA",
        "icolocal": "belgica",
        "visitante": "MARRUECOS",
        "icovisitante": "marruecos",
        "grupo": "GRUPO F",
        "fecha_n": 2,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 26,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 27,
        "dia": "DOMINGO",
        "fecha": "27/11/2022",
        "hora": "13:00",
        "local": "CROACIA",
        "icolocal": "croacia",
        "visitante": "CANADÁ",
        "icovisitante": "canada",
        "grupo": "GRUPO F",
        "fecha_n": 2,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 27,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 28,
        "dia": "DOMINGO",
        "fecha": "27/11/2022",
        "hora": "16:00",
        "local": "ESPAÑA",
        "icolocal": "espana",
        "visitante": "ALEMANIA",
        "icovisitante": "alemania",
        "grupo": "GRUPO E",
        "fecha_n": 2,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 28,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 29,
        "dia": "LUNES",
        "fecha": "28/11/2022",
        "hora": "07:00",
        "local": "CAMERÚN",
        "icolocal": "camerun",
        "visitante": "SERBIA",
        "icovisitante": "serbia",
        "grupo": "GRUPO G",
        "fecha_n": 2,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 29,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 30,
        "dia": "LUNES",
        "fecha": "28/11/2022",
        "hora": "10:00",
        "local": "COREA",
        "icolocal": "corea",
        "visitante": "GHANA",
        "icovisitante": "ghana",
        "grupo": "GRUPO H",
        "fecha_n": 2,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 30,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 31,
        "dia": "LUNES",
        "fecha": "28/11/2022",
        "hora": "13:00",
        "local": "BRASIL",
        "icolocal": "brasil",
        "visitante": "SUIZA",
        "icovisitante": "suiza",
        "grupo": "GRUPO G",
        "fecha_n": 2,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 31,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 32,
        "dia": "LUNES",
        "fecha": "28/11/2022",
        "hora": "16:00",
        "local": "PORTUGAL",
        "icolocal": "portugal",
        "visitante": "URUGUAY",
        "icovisitante": "uruguay",
        "grupo": "GRUPO H",
        "fecha_n": 2,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 32,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 33,
        "dia": "MARTES",
        "fecha": "29/11/2022",
        "hora": "12:00",
        "local": "PAÍSES BAJOS",
        "icolocal": "paisesbajos",
        "visitante": "QATAR",
        "icovisitante": "qatar",
        "grupo": "GRUPO A",
        "fecha_n": 3,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 33,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 34,
        "dia": "MARTES",
        "fecha": "29/11/2022",
        "hora": "12:00",
        "local": "ECUADOR",
        "icolocal": "ecuador",
        "visitante": "SENEGAL",
        "icovisitante": "senegal",
        "grupo": "GRUPO A",
        "fecha_n": 3,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 34,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 35,
        "dia": "MARTES",
        "fecha": "29/11/2022",
        "hora": "16:00",
        "local": "GALES",
        "icolocal": "gales",
        "visitante": "INGLATERRA",
        "icovisitante": "inglaterra",
        "grupo": "GRUPO B",
        "fecha_n": 3,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 35,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 36,
        "dia": "MARTES",
        "fecha": "29/11/2022",
        "hora": "16:00",
        "local": "IRÁN",
        "icolocal": "iran",
        "visitante": "ESTADOS UNIDOS",
        "icovisitante": "estadosunidos",
        "grupo": "GRUPO B",
        "fecha_n": 3,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 36,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 37,
        "dia": "MIÉRCOLES",
        "fecha": "30/11/2022",
        "hora": "12:00",
        "local": "TÚNEZ",
        "icolocal": "tunez",
        "visitante": "FRANCIA",
        "icovisitante": "francia",
        "grupo": "GRUPO D",
        "fecha_n": 3,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 37,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 38,
        "dia": "MIÉRCOLES",
        "fecha": "30/11/2022",
        "hora": "12:00",
        "local": "AUSTRALIA",
        "icolocal": "australia",
        "visitante": "DINAMARCA",
        "icovisitante": "dinamarca",
        "grupo": "GRUPO D",
        "fecha_n": 3,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 38,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 39,
        "dia": "MIÉRCOLES",
        "fecha": "30/11/2022",
        "hora": "16:00",
        "local": "POLONIA",
        "icolocal": "polonia",
        "visitante": "ARGENTINA",
        "icovisitante": "argentina",
        "grupo": "GRUPO C",
        "fecha_n": 3,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 39,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 40,
        "dia": "MIÉRCOLES",
        "fecha": "30/11/2022",
        "hora": "16:00",
        "local": "ARABIA SAUDITA",
        "icolocal": "arabiasaudita",
        "visitante": "MÉXICO",
        "icovisitante": "mexico",
        "grupo": "GRUPO C",
        "fecha_n": 3,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 40,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 41,
        "dia": "JUEVES",
        "fecha": "01/12/2022",
        "hora": "12:00",
        "local": "CROACIA",
        "icolocal": "croacia",
        "visitante": "BÉLGICA",
        "icovisitante": "belgica",
        "grupo": "GRUPO F",
        "fecha_n": 3,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 41,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 42,
        "dia": "JUEVES",
        "fecha": "01/12/2022",
        "hora": "12:00",
        "local": "CANADÁ",
        "icolocal": "canada",
        "visitante": "MARRUECOS",
        "icovisitante": "marruecos",
        "grupo": "GRUPO F",
        "fecha_n": 3,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 42,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 43,
        "dia": "JUEVES",
        "fecha": "01/12/2022",
        "hora": "16:00",
        "local": "JAPÓN",
        "icolocal": "japon",
        "visitante": "ESPAÑA",
        "icovisitante": "espana",
        "grupo": "GRUPO E",
        "fecha_n": 3,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 43,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 44,
        "dia": "JUEVES",
        "fecha": "01/12/2022",
        "hora": "16:00",
        "local": "COSTA RICA",
        "icolocal": "costarica",
        "visitante": "ALEMANIA",
        "icovisitante": "alemania",
        "grupo": "GRUPO E",
        "fecha_n": 3,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 44,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 45,
        "dia": "VIERNES",
        "fecha": "02/12/2022",
        "hora": "12:00",
        "local": "COREA",
        "icolocal": "corea",
        "visitante": "PORTUGAL",
        "icovisitante": "portugal",
        "grupo": "GRUPO H",
        "fecha_n": 3,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 45,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 46,
        "dia": "VIERNES",
        "fecha": "02/12/2022",
        "hora": "12:00",
        "local": "GHANA",
        "icolocal": "ghana",
        "visitante": "URUGUAY",
        "icovisitante": "uruguay",
        "grupo": "GRUPO H",
        "fecha_n": 3,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 46,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 47,
        "dia": "VIERNES",
        "fecha": "02/12/2022",
        "hora": "16:00",
        "local": "CAMERÚN",
        "icolocal": "camerun",
        "visitante": "BRASIL",
        "icovisitante": "brasil",
        "grupo": "GRUPO G",
        "fecha_n": 3,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 47,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 48,
        "dia": "VIERNES",
        "fecha": "02/12/2022",
        "hora": "16:00",
        "local": "SERBIA",
        "icolocal": "serbia",
        "visitante": "SUIZA",
        "icovisitante": "suiza",
        "grupo": "GRUPO G",
        "fecha_n": 3,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 48,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 49,
        "dia": "SÁBADO",
        "fecha": "03/12/2022",
        "hora": "12:00",
        "local": "1° A",
        "icolocal": "1°a",
        "visitante": "2° B",
        "icovisitante": "2°b",
        "grupo": "OCTAVOS DE FINAL",
        "fecha_n": 4,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 49,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 50,
        "dia": "SÁBADO",
        "fecha": "03/12/2022",
        "hora": "16:00",
        "local": "1° C",
        "icolocal": "1°c",
        "visitante": "2° D",
        "icovisitante": "2°d",
        "grupo": "OCTAVOS DE FINAL",
        "fecha_n": 4,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 50,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 51,
        "dia": "DOMINGO",
        "fecha": "04/12/2022",
        "hora": "12:00",
        "local": "1° D",
        "icolocal": "1°d",
        "visitante": "2° C",
        "icovisitante": "2°c",
        "grupo": "OCTAVOS DE FINAL",
        "fecha_n": 4,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 51,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 52,
        "dia": "DOMINGO",
        "fecha": "04/12/2022",
        "hora": "16:00",
        "local": "1° B",
        "icolocal": "1°b",
        "visitante": "2° A",
        "icovisitante": "2°a",
        "grupo": "OCTAVOS DE FINAL",
        "fecha_n": 4,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 52,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 53,
        "dia": "LUNES",
        "fecha": "05/12/2022",
        "hora": "12:00",
        "local": "1° E",
        "icolocal": "1°e",
        "visitante": "2° F",
        "icovisitante": "2°f",
        "grupo": "OCTAVOS DE FINAL",
        "fecha_n": 4,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 53,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 54,
        "dia": "LUNES",
        "fecha": "05/12/2022",
        "hora": "16:00",
        "local": "1° G",
        "icolocal": "1°g",
        "visitante": "2° H",
        "icovisitante": "2°h",
        "grupo": "OCTAVOS DE FINAL",
        "fecha_n": 4,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 54,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 55,
        "dia": "MARTES",
        "fecha": "06/12/2022",
        "hora": "12:00",
        "local": "1° F",
        "icolocal": "1°f",
        "visitante": "2° E",
        "icovisitante": "2°e",
        "grupo": "OCTAVOS DE FINAL",
        "fecha_n": 4,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 55,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 56,
        "dia": "MARTES",
        "fecha": "06/12/2022",
        "hora": "16:00",
        "local": "1° H",
        "icolocal": "1°h",
        "visitante": "2° G",
        "icovisitante": "2°g",
        "grupo": "OCTAVOS DE FINAL",
        "fecha_n": 4,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 56,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 57,
        "dia": "VIERNES",
        "fecha": "09/12/2022",
        "hora": "12:00",
        "local": "GANADOR P. 5",
        "icolocal": "ganadorp.5",
        "visitante": "GANADOR P. 6",
        "icovisitante": "ganadorp.6",
        "grupo": "CUARTOS DE FINAL",
        "fecha_n": 5,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 57,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 58,
        "dia": "VIERNES",
        "fecha": "09/12/2022",
        "hora": "16:00",
        "local": "GANADOR P. 1",
        "icolocal": "ganadorp.1",
        "visitante": "GANADOR P. 2",
        "icovisitante": "ganadorp.2",
        "grupo": "CUARTOS DE FINAL",
        "fecha_n": 5,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 58,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 59,
        "dia": "SÁBADO",
        "fecha": "10/12/2022",
        "hora": "12:00",
        "local": "GANADOR P. 7",
        "icolocal": "ganadorp.7",
        "visitante": "GANADOR P. 8",
        "icovisitante": "ganadorp.8",
        "grupo": "CUARTOS DE FINAL",
        "fecha_n": 5,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 59,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 60,
        "dia": "SÁBADO",
        "fecha": "10/12/2022",
        "hora": "16:00",
        "local": "GANADOR P. 4",
        "icolocal": "ganadorp.4",
        "visitante": "GANADOR P. 3",
        "icovisitante": "ganadorp.3",
        "grupo": "CUARTOS DE FINAL",
        "fecha_n": 5,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 60,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 61,
        "dia": "MARTES",
        "fecha": "13/12/2022",
        "hora": "16:00",
        "local": "GANADOR P. 10",
        "icolocal": "ganadorp.10",
        "visitante": "GANADOR P. 9",
        "icovisitante": "ganadorp.9",
        "grupo": "SEMIFINAL",
        "fecha_n": 6,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 61,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 62,
        "dia": "MIÉRCOLES",
        "fecha": "14/12/2022",
        "hora": "16:00",
        "local": "GANADOR P. 12",
        "icolocal": "ganadorp.12",
        "visitante": "GANADOR P. 11",
        "icovisitante": "ganadorp.11",
        "grupo": "SEMIFINAL",
        "fecha_n": 6,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 62,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 63,
        "dia": "SÁBADO",
        "fecha": "17/12/2022",
        "hora": "12:00",
        "local": "PERDEDOR P. 13",
        "icolocal": "perdedorp. 13",
        "visitante": "PERDEDOR P. 14",
        "icovisitante": "perdedorp.14",
        "grupo": "3° Y 4° PUESTO",
        "fecha_n": 7,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 63,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    },
    {
        "id": 64,
        "dia": "DOMINGO",
        "fecha": "18/12/2022",
        "hora": "12:00",
        "local": "GANADOR P. 13",
        "icolocal": "ganadorp.13",
        "visitante": "GANADOR P. 14",
        "icovisitante": "ganadorp.14",
        "grupo": "FINAL",
        "fecha_n": 7,
        "user": "prueba@prueba.com",
        "user_v": "",
        "partido_n": 64,
        "prode_resul": "",
        "prode_l": "",
        "prode_v": "",
        "prode_pl": "",
        "prode_pv": "",
        "resultado": "",
        "resul_l": "",
        "resul_v": "",
        "resul_pl": "",
        "resul_pv": "",
        "puntos": ""
    }
]